### PR TITLE
Add branch parsing with proper tests.

### PR DESCRIPTION
**Pull request by spodym**
Hi @jrit !

Current code was not parsing branch data. I have fixed it and added tests. Other changes includes:
- bumping version number
- adding `package-lock.json`
- updating and pinning dependancies

This solution fixed my issue with `vscode-coverage-gutters` not being able to show branch data. I have tested it locally and it works just fine. 

If you have any suggestions to improve this PR - please let me know and we can work on it :)

### CODE REVIEW

**Comment by jrit** [comment]
cool, thank you, and thanks for tagging me since I don't seem to have gotten a notification from the other open PR. Looks like tests are only failing for node 0.12, which I'm going to remove from support, so don't worry about that.

**Review by jrit — APPROVED** [review]

**Comment by spodym** [comment]
Okay! What about this `cvr` check? I don't see option to rerun checks.

**Comment by spodym** [comment]
@jrit Sorry for bothering you but I am not sure if you are getting notifications in this thread ;) 
Could you rerun `travis` check and see what is wrong with `cvr` check?

**Comment by jrit** [comment]
@spodym yeah, I wasn't getting notifications for a while and had some permissions issues that are resolved now. I should be cleaning things up and making a release in the next few days.

**Comment by jrit** [comment]
Fixed travis and published to npm

**Pull request merged**
