### PR TITLE
parse sparse info correctly

### PR DESCRIPTION
**Pull request by jrit**
the `<methods/>` and `<lines/>` elements don't necessarily appear in the coverage info, so this acts appropriately in their absence.

@brockboland

### CODE REVIEW

**Comment by brockboland** [comment]
LGTM, I think?

**Comment by brockboland** [comment]
@jrit could you let me know when this change is deployed? I'll re-run my job to test it.

**Comment by jrit** [comment]
already did, so go ahead

**Comment by brockboland** [comment]
Awesome, thanks!

**Pull request merged**
